name: CI

on:
  push:
    branches:
      - main
      - development
      - release

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
