name: CI

on:
  push:
    branches:
      - main
      - development
      - release
  pull_request:
         branches:
           - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: pip install -r .github/workflows/requirements.txt
    - name: Install pytest
      run: pip install pytest
    - name: Run tests
      run: python .github/workflows/test.py
    - name: install wheel
      run: pip install wheel
    - name: Build the project
      run: python .github/workflows/setup.py sdist bdist_wheel
